config/routes.rb
Rails.application.routes.draw do
  resources :nb_users

   root 'nb_users#index'

end

app/models/nb_user.rb
class NbUser < ActiveRecord::Base

#validates :external_id, :uniqueness => true

  def self.saveapi
    response =  HTTParty.get("https://brianmcauley.nationbuilder.com/api/v1/people?__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b&limit=10&__proto__=&access_token=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b",
        :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
      results = JSON.parse(response.parsed_response)['results']
      
      
      def format_results(results)
          results.map do |result| # change each -> map
              "\n\n#{ result['twitter_name'] }, #{ result['id'] }" # delete puts, [0]
  end.join # change to_sentence -> join

          text += format_results(results)
      end
      puts text
      #user_data = (@response.body)
     #@a = result.to_s[0]["twitter_name"]
     # users = user_data.map do |line|
    #  @u = NbUser.new
    #  @u.externalid.to_s = line['id']
    #  @u.lastname.to_s = line['twitter_name']
     #     puts @a
      # set name value however you want to do that
    #  @u.save
     # @u
    #end
   # users.select(&:persisted?)
  end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nb_users_controller.rb
class NbUsersController < ApplicationController
  before_action :set_nb_user, only: [:show, :edit, :update, :destroy]

  # GET /nb_users
  # GET /nb_users.json
  def index
    @nb_users = NbUser.all
    @response = HTTParty.get("https://brianmcauley.nationbuilder.com/api/v1/people?__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b&limit=200&__proto__=&access_token=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b",
 :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    @result = @response.body
    respond_to do |format|
   format.json { render :json => JSON.parse(@result) }
   format.html { render "index.html.erb" }
    end
  end

  # GET /nb_users/1
  # GET /nb_users/1.json
  def show
      response = HTTParty.get("https://brianmcauley.nationbuilder.com/api/v1/people?__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b&limit=200&__proto__=&access_token=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b",
 :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
      user = JSON.parse(response)
       user.each {|line| puts line['email']['id']}
  #the "['user']['id']" is because of the nested JSON object that is returned after the parse.
  end

  # GET /nb_users/new
  def new
    @nb_user = NbUser.new
  end

  # GET /nb_users/1/edit
  def edit
  end

  # POST /nb_users
  # POST /nb_users.json
  def create
    @nb_user = NbUser.new(nb_user_params)

    respond_to do |format|
      if @nb_user.save
        format.html { redirect_to @nb_user, notice: 'Nb user was successfully created.' }
        format.json { render :show, status: :created, location: @nb_user }
      else
        format.html { render :new }
        format.json { render json: @nb_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nb_users/1
  # PATCH/PUT /nb_users/1.json
  def update
    respond_to do |format|
      if @nb_user.update(nb_user_params)
        format.html { redirect_to @nb_user, notice: 'Nb user was successfully updated.' }
        format.json { render :show, status: :ok, location: @nb_user }
      else
        format.html { render :edit }
        format.json { render json: @nb_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nb_users/1
  # DELETE /nb_users/1.json
  def destroy
    @nb_user.destroy
    respond_to do |format|
      format.html { redirect_to nb_users_url, notice: 'Nb user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def request_from_nb

        @cfg = '__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b'
        @limit = '200'
        @access_token = 'adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b'
        @url_new_string = 'https://brianmcauley.nationbuilder.com/api/v1/people?'+@cfg+'&limit='+@limit+'&__proto__=&access_token='+@api_key
        # "https://brianmcauley.nationbuilder.com/api/v1/people?__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b&limit=200&__proto__=&access_token=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b"  - this is what is created by @url_new_string
        response =  HTTParty.get(@url_new_string.to_str)  #submit the string to get the token
        @parsed_and_a_hash = JSON.parse(response)
        @result = @parsed_and_a_hash["email"]
       # @token = @parsed_and_a_hash["token"]


        #make a new string with the token

       # @urlstring_to_post = 'https://api.squishlist.com/rest/?cfg='+@cfg+'&token='+@token+'&method=squish.issue.submit&prj='+@project

        #submit and get a result

       # @result = HTTParty.post(@urlstring_to_post.to_str, :body => {:subject => 'This is the screen name', :issue_type => 'Application Problem', :status => 'Open', :priority => 'Normal', :description => 'This is the description for the problem'})

    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nb_user
      @nb_user = NbUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nb_user_params
      params.require(:nb_user).permit(:email, :lastname, :firstname, :emailoptin, :updatedat, :externalid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nb_users_helper.rb
module NbUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NationBuilder</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nb_users/_form.html.erb
<%= form_for(@nb_user) do |f| %>
  <% if @nb_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nb_user.errors.count, "error") %> prohibited this nb_user from being saved:</h2>

      <ul>
      <% @nb_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :emailoptin %><br>
    <%= f.check_box :emailoptin %>
  </div>
  <div class="field">
    <%= f.label :updatedat %><br>
    <%= f.datetime_select :updatedat %>
  </div>
    <div class="field">
    <%= f.label :externalid %><br>
    <%= f.text_field :externalid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nb_users/edit.html.erb
<h1>Editing nb_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @nb_user %> |
<%= link_to 'Back', nb_users_path %>

app/views/nb_users/index.html.erb
<h1 style="font-size: 3em; color: darkgreen; text-align: center; font-family: Courier;">Listing nb_users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Emailoptin</th>
      <th>Updatedat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nb_users.each do |nb_user| %>
      <tr>
        <td><%= nb_user.email %></td>
        <td><%= nb_user.lastname %></td>
        <td><%= nb_user.firstname %></td>
        <td><%= nb_user.emailoptin %></td>
        <td><%= nb_user.updatedat %></td>
        <td><%= link_to 'Show', nb_user %></td>
        <td><%= link_to 'Edit', edit_nb_user_path(nb_user) %></td>
        <td><%= link_to 'Destroy', nb_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p><%= @result %></p>
<br>


<p>

 <%=     response =  HTTParty.get("https://brianmcauley.nationbuilder.com/api/v1/people?__nonce=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b&limit=200&__proto__=&access_token=adb0731da1b0cf4f6f230c898f8e746b3142a1157bcf9dd9745388f3bbe6358b",
 :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'}).parsed_response %>


</p>


<%= link_to 'New Nb user', new_nb_user_path %>

app/views/nb_users/new.html.erb
<h1>New nb_user</h1>

<%= render 'form' %>

<%= link_to 'Back', nb_users_path %>

app/views/nb_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @nb_user.email %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @nb_user.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @nb_user.firstname %>
</p>

<p>
  <strong>Emailoptin:</strong>
  <%= @nb_user.emailoptin %>
</p>

<p>
  <strong>Updatedat:</strong>
  <%= @nb_user.updatedat %>
</p>
<p>
 <%=@user.inspect%>
</p>
<%= link_to 'Edit', edit_nb_user_path(@nb_user) %> |
<%= link_to 'Back', nb_users_path %>